📘 **Note Format Guide**

This format serves as a structured guide for organizing lecture content, personal interpretation, experiments, and study-related questions.

| Type | What It Means | When I Use It |
|------|----------------|----------------|
| 📝 Lecture | Original material from the professor’s notes | When I’m referencing core concepts or provided code |
| 🗣️ In-Class Note | Verbal explanations shared during the lecture | When I want to record something the professor said in class but didn’t include in the official notes |
| ✍️ My Note | My thoughts, interpretations, or additional explanations | When I reflect on or explain something in my own words |
| 🔬 Experiment | Code I tried out or changed to explore further | When I test variations or go beyond the original example |
| ❓ Question | Questions I had while studying | When I want to revisit or research something more deeply |

📝
🗣️
✍️
🔬
❓

# 1. 강의노트 원본 및 영상 링크

[https://guebin.github.io/DL2025/posts/01wk-1.html](https://guebin.github.io/DL2025/posts/01wk-1.html)

# 2. Imports 📝

In [1]:
import torch

# 3. 환경셋팅 📝

`-` 코랩이용자: 별도의 설치 필요 없음 

- GPU 관리가 꼭 필요함!! (시험하루전날 수업 몰아서 듣지않기, 아이디만들어두기)
- 특히 시험기간에 조심하세요 

`-` 리눅스서버 사용자 (ref: <https://pytorch.org/get-started/locally/>)

```bash
conda create -n dl2025 python=3.9
conda activate dl2025 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
```

# 4. 필요한 지식 📝

`-` 선형대수학

- 벡터와 행렬
- 행렬의 곱셉
- 트랜스포즈

`-` 기초통계학(수리통계)

- 정규분포, 이항분포
- 모수, 추정
- $X_i \overset{i.i.d.}{\sim} N(0,1)$


`-` 회귀분석 

- 독립변수($y$), 설명변수($X$)
- ${\boldsymbol y} = {\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬

- 파이썬 기본문법
- 넘파이, 판다스
- 전반적인 클래스 지식 (`__init__`, `self`, ...)
- 상속

# 5. 파이토치 기본 📝

## A. torch

🗣️ torch는 numpy와 비슷 (벡터 만들기 등)

`-` 벡터

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

`-` 벡터의 덧셈

In [3]:
torch.tensor([1,2,3]) + torch.tensor([2,2,2])

tensor([3, 4, 5])

`-` 브로드캐스팅 

In [4]:
torch.tensor([1,2,3]) + 2

tensor([3, 4, 5])

## B. 벡터와 매트릭스 

🗣️ torch.tensor는 np.array와 비슷

`-` $3 \times 2$ matrix

In [5]:
torch.tensor([[1,2],[3,4],[5,6]]) 

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` $3 \times 1$ matrix = $3 \times 1$ column vector

In [6]:
torch.tensor([[1],[3],[5]]) 

tensor([[1],
        [3],
        [5]])

`-` $1 \times 2$ matrix = $1 \times 2$ row vector

In [7]:
torch.tensor([[1,2]]) 

tensor([[1, 2]])

🗣️ torch.tensor([[1,2],[3,4],[5,6]])에서 [3,4],[5,6] 삭제라고 생각

🗣️ column vector와 row vector는 구분되고 선언 방법이 다름

`-` 더하기 

***브로드캐스팅(편한거)***

In [8]:
torch.tensor([[1,2],[3,4],[5,6]]) - 1

tensor([[0, 1],
        [2, 3],
        [4, 5]])

🗣️ "matrix - scalar"는 불가능하지만 알아서 원소별로 전부 뺌

In [9]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-3],[-5]])

tensor([[0, 1],
        [0, 1],
        [0, 1]])

🗣️ (3, 2) - (3, 1)을 알아서 뺌

✍️ torch.tensor([[-1,-1],[-3, 3],[-5,-5]])

In [10]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2]])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

🗣️ (3, 2) - (1, 2)을 알아서 뺌

✍️ torch.tensor([[-1,-2],[-1,-2],[-1,-2]])

***잘못된 브로드캐스팅***

In [11]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-3,-5]])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

🗣️ 세로로 쓰거나 가로로 두 개의 원소만 썼으면 가능

✍️ torch.tensor([[-1],[-3],[-5]]) 또는 torch.tensor([[-1,-3],[-1,-3],[-1,-3]]) 등

In [12]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-2]])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

🗣️ (3, 2) - (2, 1) 는 알아서 채우기 어려우므로 error

***이상한 것***

In [13]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-2])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

🗣️ (3, 2) matrix - 길이가 2인 vector(2x1, 1x2 둘 다 아님)

🗣️ "matrix - vector"를 row vector로 해석하고 늘려서 계산한 듯

✍️ torch.tensor([[-1,-2],[-1,-2],[-1,-2]])

🔬(

- 차원 수만 알고 싶을 때 → tensor.dim() 또는 tensor.ndim
- 각 차원의 크기까지 알고 싶을 때 → tensor.shape 또는 tensor.size()

In [14]:
print(torch.tensor([[1,2],[3,4],[5,6]]).dim())
print(torch.tensor([[1,2],[3,4],[5,6]]).shape)
print(torch.tensor([-1,-2]).dim())
print(torch.tensor([-1,-2]).shape)
print(torch.tensor([[1,2],[3,4],[5,6]]).ndim)
print(torch.tensor([[1,2],[3,4],[5,6]]).size())
print(torch.tensor([-1,-2]).ndim)
print(torch.tensor([-1,-2]).size())

2
torch.Size([3, 2])
1
torch.Size([2])
2
torch.Size([3, 2])
1
torch.Size([2])


> **참고** (Chat GPT4o)

- NumPy와 PyTorch 차이 정리

| 기능         | PyTorch                | NumPy                   |
|--------------|------------------------|--------------------------|
| 차원 수       | `.dim()` 또는 `.ndim`   | `.ndim`                  |
| shape 확인   | `.shape` 또는 `.size()` | `.shape`                 |
| 크기 변경    | `.view()`, `.reshape()` | `.reshape()`             |
| 타입         | `torch.Tensor`         | `np.ndarray`             |

- 실전 팁:
    - **PyTorch의 `.dim()`만 NumPy에서 안 먹힌다**는 것만 기억하면 둘 다 거의 비슷하게 다룰 수 있음
    - 다차원 배열을 다룰 때 `.ndim`, `.shape`는 양쪽 모두 안전하게 쓸 수 있는 핵심 도구
    - `dim()`은 PyTorch 고유 메서드

)🔬

In [15]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-3,-5])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

🗣️ 길이가 3인 vector를 column vector로 해석하고 (3,2)로 채워서 계산할 것 같지만 X (이번에 발견)

`-` 행렬곱

***정상적인 행렬곱***

In [16]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1],[2]])

tensor([[ 5],
        [11],
        [17]])

🗣️ (3,2) matirx @ (2,1) vector = (3,1) matrix

In [17]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) 

tensor([[22, 28]])

🗣️ (1,3) @ (3,2) = (1,2)

***잘못된 행렬곱***

In [18]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1,2]])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

🗣️ (3,2) @ (1,2) 불가

In [19]:
torch.tensor([[1],[2],[3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x2)

🗣️ (3,1) @ (3,2) 불가

***이상한 것***

In [20]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([1,2]) # 이게 왜 가능..

tensor([ 5, 11, 17])

🗣️ (3,2) @ (2) 길이가 2인 vector / 사람마다 해석 애매 (2,1)? (1,2)? / 곱하기를 위해 (2,1) column vector로 해석

🗣️ (3,2) @ (2,1)로 해석 후 계산하여 (3) 길이가 3인 vector가 나옴

In [21]:
torch.tensor([1,2,3]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 이건 왜 가능?

tensor([22, 28])

🗣️ (3) @ (3,2)에서 (3)을 (1,3) row vector로 해석

🗣️( 엄밀하게 하려면

In [22]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]])

tensor([[22, 28]])

✍️ 당연히 결과의 차원도 다름

)🗣️

## C. transpose, reshape

`-` transpose 

In [23]:
torch.tensor([[1,2],[3,4]]).T 

tensor([[1, 3],
        [2, 4]])

In [24]:
torch.tensor([[1],[3]]).T 

tensor([[1, 3]])

🗣️ column vector -> row vector

In [25]:
torch.tensor([[1,2]]).T 

tensor([[1],
        [2]])

🗣️ row vector -> column vector

🗣️ 차원을 바꾸는 효과 (1,2) -> (2,1)

`-` reshape

🗣️( 차원 보기

In [26]:
torch.tensor([[1,2]]).shape

torch.Size([1, 2])

을 column vector로 바꾸고 싶으면

In [27]:
torch.tensor([[1,2]]).reshape(2,1)

tensor([[1],
        [2]])

transpose와 동일

)🗣️

***일반적인 사용***

In [28]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [30]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

🗣️ (3,2) -> (1,6)

In [31]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6)

tensor([1, 2, 3, 4, 5, 6])

🗣️ (3,2)를 그냥 6으로 : 길이가 6인 vector로 바꿈

***편한 것***

In [32]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,-1)

tensor([[1, 2, 3],
        [4, 5, 6]])

🗣️ torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,??)를 원할 때 ??를 알아서 맞춤 (불가능하면 error)

In [33]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6,-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [34]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [35]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1)

tensor([1, 2, 3, 4, 5, 6])

🗣️ 전체를 vector로 바꾸고 싶을 때 (1차원)

## D. concat, stack $(\star\star\star)$

`-` concat 

In [36]:
a = torch.tensor([[1],[3],[5]])
b = torch.tensor([[2],[4],[6]])
torch.concat([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

🗣️(

In [37]:
a

tensor([[1],
        [3],
        [5]])

In [38]:
b

tensor([[2],
        [4],
        [6]])

a와 b를 모두 vector로 갖고 있는데 [a b]처럼 놓고 싶을 때 사용

In [39]:
a, b

(tensor([[1],
         [3],
         [5]]),
 tensor([[2],
         [4],
         [6]]))

In [40]:
torch.concat([a,b]) # 이렇게 하면 좌우가 아니라 위 아래로 합쳐짐

tensor([[1],
        [3],
        [5],
        [2],
        [4],
        [6]])

(3,1)과 (3,1)을 (3,2)로 만들고 싶었는데 (6,1)이 됨 -> axis=1 옵션 사용하면 (3,2) 가능 (모르겠으면 밑의 링크 참조)

)🗣️

In [41]:
torch.concat([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` stack

In [42]:
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
torch.stack([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

🗣️(

In [43]:
a

tensor([1, 3, 5])

In [44]:
b

tensor([2, 4, 6])

In [45]:
a.reshape(3,1) # 참고) concat 설명 예시와 동일

tensor([[1],
        [3],
        [5]])

In [46]:
torch.concat([a.reshape(3,1), b.reshape(3,1)], axis=1) # 리스트로 만든 후 이렇게 하면 되긴하나 너무 힘듦

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [47]:
torch.stack([a,b], axis=1) # 같은 결과

tensor([[1, 2],
        [3, 4],
        [5, 6]])

차이: concat은 바꾸려는 대상의 dimension을 바꾸지는 X (matrix는 matrix로, vector는 vector로) / stack은 dimension을 하나 늘려서 바꿔줌

concat과 stack 둘 다 알면 좋음

)🗣️

In [48]:
torch.concat([a.reshape(3,1),b.reshape(3,1)],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

:::{.callout-warning}

concat과 stack을 지금 처음본다면 아래를 복습하시는게 좋습니다. 

<https://guebin.github.io/PP2024/posts/06wk-2.html#numpy와-축axis>
:::