> 문제풀이에 필요한 모듈은 스스로 `import` 할 것

In [1]:
import torch

# `#` --기본문법 

## `$`. 벡터와 행렬 

`(1)` 아래와 같이 length 5 인 vector를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf x} = [1,2,3,4,5]$$ 

`(풀이)`

In [2]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

`(2)` 아래와 같은 2x2 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$ 

`(풀이?)`

In [3]:
A = torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

`(3)` 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf W} = \begin{bmatrix} 2.5  \\  4 \end{bmatrix}$$ 

`(풀이?)`

In [4]:
W = torch.tensor([[2.5],[4]])
W

tensor([[2.5000],
        [4.0000]])

`(4)` 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf x} = \begin{bmatrix} 2.5  & 4 \end{bmatrix}$$ 

`(풀이?)`

In [5]:
x = torch.tensor([[2.5, 4]])
x

tensor([[2.5000, 4.0000]])

## `$`. concat, stack

a,b가 아래와 같이 주어졌다고 하자.


In [6]:
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)

`(관찰?)`

In [7]:
a

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
a.shape

torch.Size([10])

In [9]:
b

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`(실험?)`

In [10]:
torch.tensor([[1]*10])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
torch.tensor([[1]*10]).shape

torch.Size([1, 10])

아래를 잘 읽고 물음에 답하라. 

`(1)` 주어진 a,b와 `torch.concat`를 이용하여 아래와 같은 배열을 만들어라.

```
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
```

`(풀이?)`

In [12]:
torch.concat([a,b])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`(2)` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])
```

`(풀이)`

In [13]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])

`(관찰?)`

In [14]:
a.reshape(-1,1)

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]])

In [15]:
a

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

`(3)` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])
```

`(풀이?)`

In [16]:
torch.concat([a,b])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
torch.concat([a,b]).reshape(-1,2)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2]])

In [18]:
torch.concat([a.reshape(-1,1),b.reshape(-1,1)], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

`(4)` 주어진 a,b와 `torch.stack` 을 이용하여 아래와 같은 배열을 만들어라.

```
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
```

`(풀이?)`

In [19]:
torch.stack([a,b])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

`(관찰?)`

In [20]:
torch.stack([a,b], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

`(5)` 주어진 a,b와 `torch.stack`을 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])
```

`(풀이?)`

In [21]:
torch.stack([a,b], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

## `$`. 행렬곱 

`(1)` 아래와 같은 텐서를 고려하자. 

In [22]:
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)

`@` 연산자를 이용하여 $\sum_{i=1}^{5}a_ib_i$를 계산하라.

`(풀이)`

In [23]:
a.T @ b

tensor([[24]])

`(2)` 아래와 같은 텐서를 고려하자. 

In [24]:
torch.manual_seed(0)
x = torch.randn(100).reshape(-1,1)

`@`연산자를 이용하여 $\sum_{i=1}^{100}x_i^2$을 계산하라.

`(풀이?)`

In [25]:
x.T @ x

tensor([[105.0856]])

## `$`. 인덱싱 

아래와 같은 배열을 선언하라.

In [26]:
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

`(1)` 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])
```

`(풀이?)`

In [27]:
x[:,0]

tensor([ 0.6614, -0.4519, -1.0276])

In [28]:
x[:,0].reshape(-1,1)

tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])

In [29]:
x[:,0].unsqueeze(1)

tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])

`(2)` 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])
```

`(풀이?)`

In [30]:
x[:,1:3]

tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])

In [31]:
x[:,[1,2]]

tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])

`(3)` 2-3행을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

```

`(풀이?)`

In [32]:
x[1:,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

In [33]:
x[1:3,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

In [34]:
x[[1,2],:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

`(관찰?)`

In [35]:
x[1:2,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817]])

## `$`. `torch.einsum`

In [36]:
X = torch.randn(5,2)
X

tensor([[-0.1955, -0.9656],
        [ 0.4224,  0.2673],
        [-0.4212, -0.5107],
        [-1.5727, -0.1232],
        [ 3.5870, -1.8313]])

`(1)` 아래에 대응하는 코드를 `torch.einsum`으로 구현하라. 

In [37]:
X.t()

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

`(풀이?)`

In [38]:
torch.einsum('ij->ji', X)

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

# ChatGPT 4o 🔬❓

## Q1

> `unsqueeze`를 쓰지 않고 열 벡터를 뽑았을 때 `.shape` 차이점은?

### 예제 비교

```python
x[:, 0]           # unsqueeze 없이
x[:, 0].unsqueeze(1)  # unsqueeze 사용
```

#### 1. `x[:, 0]`

* **결과 텐서 shape**: `torch.Size([3])`
* **설명**: 1열의 값을 *1차원 벡터*로 반환한다.
  예: `[0.6614, -0.4519, -1.0276]`

#### 2. `x[:, 0].unsqueeze(1)`

* **결과 텐서 shape**: `torch.Size([3, 1])`
* **설명**: 열 방향으로 *2차원 텐서*로 만든다.
  예: `[[0.6614], [-0.4519], [-1.0276]]`

### 차이점 요약

| 항목     | `x[:, 0]`   | `x[:, 0].unsqueeze(1)` |
| ------ | ----------- | ---------------------- |
| shape  | `[3]`       | `[3, 1]`               |
| 차원 수   | 1차원 (벡터)    | 2차원 (행렬)               |
| 브로드캐스팅 | 자동으로 확장 어려움 | 다른 행렬과 곧바로 연산 가능       |

#### 언제 `unsqueeze(1)`를 써야 하나?

* 모델에 입력할 때 (예: `[batch, features]` 형태)
* 행렬 연산에서 차원 일치를 맞춰야 할 때
* 시각화 시 열 벡터 형태로 유지하고 싶을 때

## Q2

> `x[:, 1:3]` vs. `x[:, [1, 2]]` 차이점

### 1. `x[:, 1:3]` — **슬라이싱**

* 연속된 구간을 **slice 객체**로 추출
* 결과는 **연속된 메모리 블록**이므로 `뷰(view)`가 됨 → 원본 변경 시 반영 가능
* 메모리 효율적
* 인덱스는 `start:end`로, `end`는 **포함하지 않음**

```python
x[:, 1:3]  # 열 1번과 2번
```

### 2. `x[:, [1, 2]]` — **Fancy Indexing**

* 리스트로 지정한 인덱스들을 **직접 선택**
* `복사본(copy)`이 생성되므로 원본 변경과 연결되지 않음
* 연속된 열뿐 아니라 **임의의 순서**, **중복**, **불연속 인덱스**도 가능

```python
x[:, [1, 2]]       # 열 1번과 2번 (복사본)
x[:, [2, 1, 2]]    # 열 순서, 중복도 가능
```

### 차이 예시

| 항목            | `x[:, 1:3]` | `x[:, [1, 2]]`    |
| ------------- | ----------- | ----------------- |
| 연속된 열만 선택 가능  | ✅           | ✅                 |
| 불연속 열 선택      | ❌           | ✅                 |
| 중복 열 선택       | ❌           | ✅ (`[2, 1, 2]` 등) |
| 반환값이 뷰(view)? | ✅           | ❌ (copy)          |
| 메모리 효율        | 높음          | 낮음 (복사 발생)        |

## Q3

> `x[1:3, :]` vs. `x[-2:, :]` 관계

### 동일한 결과를 만듦

둘 다 `2~3행(인덱스 1, 2)`을 선택하는 코드다.

```python
x[1:3, :]    # 행 인덱스 1~2
x[-2:, :]    # 끝에서 두 번째부터 끝까지 = 인덱스 1~2
```

| 표현          | 의미               | 행 추출 결과   |
| ----------- | ---------------- | --------- |
| `x[1:3, :]` | 1번째부터 2번째까지 슬라이싱 | `[1, 2]행` |
| `x[-2:, :]` | 뒤에서 2개 슬라이싱      | `[1, 2]행` |

### 차이점

* `x[1:3, :]`은 **정방향 인덱스**로 위치를 기준
* `x[-2:, :]`은 **역방향 인덱스**로 끝 기준 → 가변 길이 텐서에서 유용

## Q2 Q3 정리 포인트

| 비교 대상                       | 차이점 요약                                |
| --------------------------- | ------------------------------------- |
| `[:, 1:3]` vs `[:, [1, 2]]` | 전자는 **연속 구간 슬라이싱**, 후자는 **지정된 열 복사**  |
| `[1:3, :]` vs `[-2:, :]`    | 결국 **같은 행 추출**, 접근 방식(앞 vs. 뒤 기준)만 다름 |

## Q4

> `unsqueeze`에 대해 설명

- `unsqueeze`는 텐서 차원을 **인위적으로 추가**하는 함수로, PyTorch에서 데이터를 다룰 때 매우 자주 쓰인다.
- 차원이 맞지 않아 오류가 발생할 때, `unsqueeze`를 이용하면 이를 간단하게 해결할 수 있다.

### `torch.unsqueeze(tensor, dim)` 또는 `tensor.unsqueeze(dim)`

#### 역할:

* **지정한 위치 `dim`에 크기 1짜리 차원을 추가**한다.
* 결과 텐서의 shape은 원래보다 **차원이 1 증가**한다.

#### 예시 1: 벡터 → 열 벡터

```python
x = torch.tensor([1, 2, 3])       # shape: [3]
x_unsq = x.unsqueeze(1)           # shape: [3, 1]

# 결과:
# tensor([[1],
#         [2],
#         [3]])
```

#### 예시 2: 벡터 → 배치 텐서

```python
x = torch.tensor([1, 2, 3])       # shape: [3]
x_unsq = x.unsqueeze(0)           # shape: [1, 3]

# 결과:
# tensor([[1, 2, 3]])
```

#### Shape 변화 정리:

| 원래 shape | `unsqueeze(0)` | `unsqueeze(1)` | `unsqueeze(-1)` |
| -------- | -------------- | -------------- | --------------- |
| `[3]`    | `[1, 3]`       | `[3, 1]`       | `[3, 1]`        |
| `[3, 4]` | `[1, 3, 4]`    | `[3, 1, 4]`    | `[3, 4, 1]`     |

### 주로 사용하는 상황

#### 1. **모델 입력 차원 맞추기**

```python
x = torch.tensor([1.0, 2.0, 3.0])  # shape [3]
x = x.unsqueeze(0)  # shape [1, 3] → batch 차원 추가
```

#### 2. **브로드캐스팅 용도**

```python
a = torch.tensor([1, 2, 3])         # shape: [3]
b = a.unsqueeze(1)                  # shape: [3, 1]
```

→ 이후 연산 시 자동으로 `[3, 1]`과 `[3, 4]` 같은 텐서가 맞춰짐

### 주의

* `unsqueeze`는 실제 데이터를 바꾸지 않고 **shape만 변경**한다.
* 원래의 텐서와 동일한 메모리 참조를 가질 수도 있음 (즉, view일 수 있음)

### 관련 함수

| 함수          | 기능                        |
| ----------- | ------------------------- |
| `unsqueeze` | **차원 추가**                 |
| `squeeze`   | **크기 1인 차원 제거**           |
| `reshape`   | 전체 차원을 원하는 형태로 재구성        |
| `view`      | reshape과 거의 동일, 메모리 연속 요구 |

In [39]:
torch.unsqueeze?

Docstring:
unsqueeze(input, dim) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.

The returned tensor shares the same underlying data with this tensor.

A :attr:`dim` value within the range ``[-input.dim() - 1, input.dim() + 1)``
can be used. Negative :attr:`dim` will correspond to :meth:`unsqueeze`
applied at :attr:`dim` = ``dim + input.dim() + 1``.

Args:
    input (Tensor): the input tensor.
    dim (int): the index at which to insert the singleton dimension

Example::

    >>> x = torch.tensor([1, 2, 3, 4])
    >>> torch.unsqueeze(x, 0)
    tensor([[ 1,  2,  3,  4]])
    >>> torch.unsqueeze(x, 1)
    tensor([[ 1],
            [ 2],
            [ 3],
            [ 4]])
Type:      builtin_function_or_method

## Q5

> `torch.einsum`에 대한 설명

- `torch.einsum`은 `Einstein summation (아인슈타인 표기법)`을 사용해 텐서 연산을 간결하고 직관적으로 표현할 수 있는 강력한 도구

### `torch.einsum`이란?

- `einsum`은 "어떤 차원을 기준으로 계산하고, 어떤 차원을 남길지"를 **직접 지정**하는 방식
- 불필요한 `reshape`, `transpose`, `sum` 등을 따로 하지 않아도 **한 줄로 연산 가능**

### 기본 문법

```python
torch.einsum('input_indices->output_indices', operands)
```

예:

```python
torch.einsum('ij->ji', X)       # 전치 transpose
torch.einsum('ij,jk->ik', A, B) # 행렬 곱 A @ B
```

### 기본 예제 모음

#### 전치: `X.t()`

```python
torch.einsum('ij->ji', X)
```

#### 행렬 곱: `A @ B`

```python
torch.einsum('ik,kj->ij', A, B)
```

설명:

* `i`: A의 행 인덱스
* `k`: A의 열 = B의 행 (sum 대상)
* `j`: B의 열

#### 벡터 내적: `torch.dot(a, b)`

```python
torch.einsum('i,i->', a, b)  # 결과: 스칼라
```

#### 배치 행렬 곱: `torch.bmm(A, B)`

```python
torch.einsum('bij,bjk->bik', A, B)
```

#### 열별 합계: `torch.sum(X, dim=0)`

```python
torch.einsum('ij->j', X)
```

### 장점 요약

| 장점          | 설명                                               |
| ----------- | ------------------------------------------------ |
| 직관적인 인덱스 지정 | 원하는 차원을 남기거나 더할 수 있음                             |
| 복잡한 연산 단순화  | `matmul`, `sum`, `permute`, `reshape` 등을 한 줄로 처리 |
| 메모리 효율적     | 불필요한 중간 텐서 생성 없음                                 |

### 시각적으로 이해

```
# 예: 행렬 곱 A @ B

A.shape = (2, 3)     => 'ik'
B.shape = (3, 4)     => 'kj'
결과: torch.einsum('ik,kj->ij', A, B)  → shape (2, 4)
```

### 유의사항

* `'ij->ji'`처럼 `화살표(->)`는 "이 인덱스들을 어떻게 재구성할 것인지"를 뜻함
* 같은 문자가 **두 번 이상 등장**하면 그 차원을 **summation** (축소) 대상으로 봄
* 없는 차원에 대한 문자는 오류를 발생시킴

In [41]:
# torch.einsum?

## Q6

> `einsum`을 사용할 때, 브로드캐스팅과 차원 축소는 어떻게 동작?

- 이건 `einsum`의 핵심 작동 원리이자 큰 강점 중 하나

### `차원 축소 (Reduction)`

`einsum`에서 **같은 문자가 두 번 등장하면**, 그 차원은 `sum (합산)` 처리됨

#### 예시: 벡터 내적

```python
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
torch.einsum('i,i->', a, b)
```

* `'i,i->'`는 i끼리 곱하고 → **모든 i에 대해 합**.
* 결과: `1×4 + 2×5 + 3×6 = 32`

\=> 결과는 **스칼라** (0차원 텐서)

### `브로드캐스팅 (Broadcasting)`

* `einsum`은 **자동 브로드캐스팅을 지원하지 않음**
* 하지만 인덱스 차원을 명시하면, **명시적 브로드캐스팅처럼 작동**시킬 수 있음

#### 예시: 외적 (outer product)

```python
a = torch.tensor([1.0, 2.0, 3.0])   # shape [3]
b = torch.tensor([4.0, 5.0])        # shape [2]

torch.einsum('i,j->ij', a, b)
```

* 결과: shape `[3, 2]`
* `i`는 a의 차원, `j`는 b의 차원 → 각각 브로드캐스트해서 곱함

```
[[1*4, 1*5],
 [2*4, 2*5],
 [3*4, 3*5]]
```

### 예제 하나로 축소 vs 브로드캐스팅 비교

```python
X = torch.randn(3, 4)

# 열별 합계 (축소)
torch.einsum('ij->j', X)   # shape: [4]

# 행별 합계 (축소)
torch.einsum('ij->i', X)   # shape: [3]

# 자기 자신과의 외적 (브로드캐스팅)
torch.einsum('i,j->ij', X[0], X[1])
```

### 핵심 요약표

| 표현          | 의미                            |
| ----------- | ----------------------------- |
| `'ij->j'`   | i 차원을 **sum** → 열 합계          |
| `'i,i->'`   | i 차원을 **sum** → 내적 (스칼라)      |
| `'i,j->ij'` | 브로드캐스트 곱 → 외적 (Outer Product) |

### 정리

* `einsum`에서 `같은 문자가 두 번 등장하면 → 축소(sum)`
* **다른 문자끼리는 → 브로드캐스트**
* 브로드캐스트는 자동이 아니라, **명시된 인덱스로 의도적으로 설계**

## 추가 질문들

- `einsum('bij,bjk->bik')`은 어떤 차원 연산을 수행하는가? 직접 shape 예시로 설명해봐.

- `einsum`을 사용해 MSE (Mean Squared Error)를 한 줄로 계산하려면 어떤 식이 될까?

- `einsum`의 표현력을 이용해 CNN 필터 적용 전 dot product를 명시적으로 작성해볼 수 있을까?