> 문제풀이에 필요한 모듈은 스스로 `import` 할 것

In [1]:
import torch

# `#` --기본문법 

## `$`. 벡터와 행렬 

`(1)` 아래와 같이 length 5 인 vector를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf x} = [1,2,3,4,5]$$ 

`(풀이)`

In [2]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

`(2)` 아래와 같은 2x2 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$ 

`(풀이?)`

In [3]:
A = torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

`(3)` 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf W} = \begin{bmatrix} 2.5  \\  4 \end{bmatrix}$$ 

`(풀이?)`

In [4]:
W = torch.tensor([[2.5],[4]])
W

tensor([[2.5000],
        [4.0000]])

`(4)` 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라. 

$${\bf x} = \begin{bmatrix} 2.5  & 4 \end{bmatrix}$$ 

`(풀이?)`

In [5]:
x = torch.tensor([[2.5, 4]])
x

tensor([[2.5000, 4.0000]])

## `$`. concat, stack

a,b가 아래와 같이 주어졌다고 하자.


In [6]:
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)

`(관찰?)`

In [7]:
a

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
a.shape

torch.Size([10])

In [9]:
b

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`(실험?)`

In [10]:
torch.tensor([[1]*10])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
torch.tensor([[1]*10]).shape

torch.Size([1, 10])

아래를 잘 읽고 물음에 답하라. 

`(1)` 주어진 a,b와 `torch.concat`를 이용하여 아래와 같은 배열을 만들어라.

```
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
```

In [12]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])

`(풀이?)`

In [13]:
torch.concat([a,b])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`(2)` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])
```

`(풀이)`

In [14]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])

`(관찰?)`

In [15]:
a.reshape(-1,1)

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]])

In [16]:
a

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

`(3)` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])
```

`(풀이?)`

In [17]:
torch.concat([a,b])

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
torch.concat([a,b]).reshape(-1,2)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2]])

In [19]:
torch.concat([a.reshape(-1,1),b.reshape(-1,1)], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

`(4)` 주어진 a,b와 `torch.stack` 을 이용하여 아래와 같은 배열을 만들어라.

```
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
```

`(풀이?)`

In [20]:
torch.stack([a,b])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

`(관찰?)`

In [21]:
torch.stack([a,b], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

`(5)` 주어진 a,b와 `torch.stack`을 이용하여 아래와 같은 배열을 만들어라.
```
tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])
```

`(풀이?)`

In [22]:
torch.stack([a,b], axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

## `$`. 행렬곱 

`(1)` 아래와 같은 텐서를 고려하자. 

In [23]:
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)

`@` 연산자를 이용하여 $\sum_{i=1}^{5}a_ib_i$를 계산하라.

`(풀이)`

In [24]:
a.T @ b

tensor([[24]])

`(2)` 아래와 같은 텐서를 고려하자. 

In [25]:
torch.manual_seed(0)
x = torch.randn(100).reshape(-1,1)

`@`연산자를 이용하여 $\sum_{i=1}^{100}x_i^2$을 계산하라.

`(풀이?)`

In [26]:
x.T @ x

tensor([[105.0856]])

In [27]:
y = x.squeeze()
y @ y

tensor(105.0856)

## `$`. 인덱싱 

아래와 같은 배열을 선언하라.

In [28]:
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

`(1)` 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])
```

`(풀이?)`

In [29]:
x[:,0]

tensor([ 0.6614, -0.4519, -1.0276])

In [30]:
x[:,0].reshape(-1,1)

tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])

In [31]:
x[:,0].unsqueeze(1)

tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])

`(2)` 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])
```

`(풀이?)`

In [32]:
x[:,1:3]

tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])

In [33]:
x[:,[1,2]]

tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])

`(3)` 2-3행을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

```
tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

```

`(풀이?)`

In [34]:
x[1:,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

In [35]:
x[1:3,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

In [36]:
x[[1,2],:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

`(관찰?)`

In [37]:
x[1:2,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817]])

## `$`. `torch.einsum`

`(1)` 아래에 코드중 `X.t()`에 대응하는 코드를 `torch.einsum`으로 구현하라. 

In [38]:
X = torch.randn(5,2)
X.t()

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

`(풀이?)`

In [39]:
torch.einsum('ij->ji', X)

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

`(2)` 아래에 코드중 `X@b`에 대응하는 코드를 `torch.einsum`으로 구현하라. 

In [40]:
X = torch.randn(5,2)
b = torch.randn(2,1)
X@b

tensor([[ 3.0610],
        [ 1.1183],
        [-5.5600],
        [ 2.2772],
        [-1.3251]])

`(풀이?)`

In [41]:
torch.einsum('ij,jk->ik', X, b)

tensor([[ 3.0610],
        [ 1.1183],
        [-5.5600],
        [ 2.2772],
        [-1.3251]])

`(3)` 아래에 코드중 `linr(X)`에 대응하는 코드를 `torch.einsum`으로 구현하라. 

In [42]:
X =  torch.randn(5,2)
linr = torch.nn.Linear(2,1,bias=False)
linr(X)

tensor([[-0.1186],
        [-0.1857],
        [ 0.1783],
        [ 0.2444],
        [ 0.4162]], grad_fn=<MmBackward0>)

`(풀이?)`

In [43]:
W = linr.weight

In [44]:
W.shape

torch.Size([1, 2])

In [45]:
torch.einsum('ij,kj->ik', X, W)   # shape: (5,1)

tensor([[-0.1186],
        [-0.1857],
        [ 0.1783],
        [ 0.2444],
        [ 0.4162]], grad_fn=<ViewBackward0>)

# `#` -- parameter count 

`(1)` 아래의 네트워크에서 학습가능한 파라메터수를 count하라. 

In [46]:
net = torch.nn.Sequential(
    torch.nn.Linear(10,2,bias=False),
    torch.nn.Sigmoid(),
    torch.nn.Linear(2,1,bias=False)
)

(풀이1)

In [47]:
10*2  + 2*1

22

(풀이2)

In [48]:
para_list = list(net.parameters())

In [49]:
len(para_list)

2

In [50]:
para_list[0].shape

torch.Size([2, 10])

In [51]:
para_list[1].shape

torch.Size([1, 2])

따라서 2\*10+1\*2 = 22 

(풀이3)

In [52]:
total = 0 
for para in net.parameters():
    total = total + torch.prod(torch.tensor(para.shape))
total

tensor(22)

`(2)` 아래의 네트워크에서 학습가능한 파라메터수를 count하라. 

In [53]:
net = torch.nn.Sequential(
    torch.nn.Conv2d(in_channels=3, out_channels=5, kernel_size=(5,5),bias=False)
)

`(풀이1)`

In [54]:
3*5*25

375

`(풀이2)`

In [55]:
total = 0 
for para in net.parameters():
    total = total + torch.prod(torch.tensor(para.shape))
total

tensor(375)